name: Docker Image GPU

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: quantum-rl-gpu
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Dockerimage
      run: docker build . -f Dockerfile_GPU -t ${{ env.IMAGE_NAME }}:latest
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Tag Docker image
      run: docker image tag ${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/lfd/${{ env.IMAGE_NAME }}:latest
      
    - name: Push Docker image
      run: docker image push ${{ env.REGISTRY }}/lfd/${{ env.IMAGE_NAME }}:latest
